#!/usr/bin/env bash
# Auto-generated by workspace-configurator. DO NOT EDIT.
set -e

echo "=== Starting Multi-Repo Workspace Clone ==="

if [ ! -d "/workspaces/mda" ]; then
    echo "Cloning michaeldallen/mda..."
    git clone "https://github.com/michaeldallen/mda.git" "/workspaces/mda"
else
    echo "Repository mda already exists."
fi

if [ ! -d "/workspaces/mdabone" ]; then
    echo "Cloning michaeldallen/mdabone..."
    git clone "https://github.com/michaeldallen/mdabone.git" "/workspaces/mdabone"
else
    echo "Repository mdabone already exists."
fi

echo "=== Multi-Repo Workspace Clone Complete ==="
